version: "3.9"

services:
  app:
    build:
      context: ./docker/app
    container_name: microloja_app
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - microloja

  composer:
    image: composer:2
    container_name: composer
    working_dir: /var/www
    volumes:
      - ./backend:/var/www
    networks:
      - microloja

  nginx:
    image: nginx:alpine
    container_name: microloja_nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - microloja

  mysql:
    image: mysql:8.0
    container_name: microloja_mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: microloja
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - microloja

networks:
  microloja:

volumes:
  mysql_data:
